// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Jun 24 00:03:00 2012

#include <wx/wx.h>
#include <wx/image.h>

#include <vector>
#include <string>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef FILTERERRORDIALOG_H
#define FILTERERRORDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade


class FilterErrorDialog: public wxDialog {
public:
    // begin wxGlade: FilterErrorDialog::ids
    // end wxGlade

    FilterErrorDialog(wxWindow* parent, int id=wxID_ANY, const wxString& title=_("Filter Errors"), const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    void SetText(const std::vector<std::string> &text);
private:
    // begin wxGlade: FilterErrorDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: FilterErrorDialog::attributes
    wxTextCtrl* textErrorMessage;
    wxStaticBitmap* bitmapError;
    wxStaticText* labelError;
    wxStaticBitmap* bitmapWarning;
    wxStaticText* labelWarning;
    wxButton* btnOK;
    // end wxGlade
}; // wxGlade: end class


#endif // FILTERERRORDIALOG_H
