// -*- C++ -*- generated by wxGlade 0.6.5 on Tue Aug 28 22:07:07 2012

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef REALKEYFRAMEDIALOG_H
#define REALKEYFRAMEDIALOG_H

enum
{
	TRANSITION_STEP,
	TRANSITION_INTERP,
	TRANSITION_END
};


// begin wxGlade: ::extracode
enum
{
	ID_COMBO_TRANSITION,
	ID_TEXT_FRAME_START,
	ID_TEXT_FRAME_END,
	ID_TEXT_FINAL_VALUE,
	ID_TEXT_INITIAL_VALUE,
};
// end wxGlade

template<class T>
class RealKeyFrameDialog: public wxDialog
{
public:
	// begin wxGlade: RealKeyFrameDialog::ids
	// end wxGlade

	RealKeyFrameDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	//!Return the keyframe transition style selected by user
	size_t getTransitionMode() const { return transitionMode;}

	//!Return the initial frame from user
	size_t getEndFrame() const { return endFrame;}
	//!Return the start frame, as was given by user
	size_t getStartFrame() const { return startFrame;}

	//!Return the initial value, as given by user 
	T getEndValue() const { return endValue;}
	//!Return the start value, as was given by user 
	T getStartValue() const { return startValue;}
private:
	size_t transitionMode;
	size_t startFrame, endFrame;
	T startValue, endValue;

	bool startFrameOK,endFrameOK;
	bool startValueOK,endValueOK;

	void updateOKButton();

	// begin wxGlade: RealKeyFrameDialog::methods
	void set_properties();
	void do_layout();
	// end wxGlade

protected:
	// begin wxGlade: RealKeyFrameDialog::attributes
	wxStaticBox* sizerMainArea_staticbox;
	wxStaticText* labelTransition;
	wxComboBox* comboTransition;
	wxStaticText* labelFrameStart;
	wxTextCtrl* textFrameStart;
	wxStaticText* labelFrameEnd;
	wxTextCtrl* textFrameEnd;
	wxStaticLine* verticalLine;
	wxStaticText* labelStartVal;
	wxTextCtrl* textStartVal;
	wxStaticText* labelEndVal;
	wxTextCtrl* textEndVal;
	wxButton* buttonCancel;
	wxButton* buttonOK;
	// end wxGlade

	DECLARE_EVENT_TABLE();

public:
	virtual void OnComboTransition(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTextStartFrame(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTextEndFrame(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTextStartValue(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnTextEndValue(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class

#include "realKeyFrameDialog.cpp"


#endif // REALKEYFRAMEDIALOG_H
