// -*- C++ -*-
//
// generated by wxGlade 0.6.8 on Sun Nov 10 18:05:15 2013
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef PREFDIALOG_H
#define PREFDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>
#include "wx/intl.h"

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/grid.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class PrefDialog: public wxDialog {
public:
    // begin wxGlade: PrefDialog::ids
    // end wxGlade

    PrefDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: PrefDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PrefDialog::attributes
    wxStaticBox* sizerCamSpeed_staticbox;
    wxStaticBox* sizer_7_staticbox;
    wxStaticBox* updateSizer_staticbox;
    wxStaticBox* sizer_2_staticbox;
    wxStaticBox* filterPropSizer_staticbox;
    wxStaticText* lblFilters;
    wxListBox* listFilters;
    wxGrid* filterGridProperties;
    wxButton* filterBtnResetAllFilters;
    wxButton* filterResetDefaultFilter;
    wxPanel* panelFilters;
    wxComboBox* comboPanelStartMode;
    wxCheckBox* chkControl;
    wxCheckBox* chkRawData;
    wxCheckBox* chkPlotlist;
    wxCheckBox* checkAllowOnlineUpdate;
    wxPanel* panelStartup;
    wxCheckBox* chkPreferOrtho;
    wxStaticText* lblMoveSpeed;
    wxStaticText* labelSlowCamMoveRate;
    wxSlider* sliderCamMoveRate;
    wxStaticText* labelFastCamMoveRate;
    wxStaticText* lblZoomSpeed;
    wxStaticText* labelSlowCamZoomRate;
    wxSlider* sliderCamZoomRate;
    wxStaticText* labelSlowFastZoomRate;
    wxPanel* notePrefPanels_pane_3;
    wxNotebook* notePrefPanels;
    wxButton* btnOK;
    wxButton* btnCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnListClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnFilterCellChange(wxGridEvent &event); // wxGlade: <event_handler>
    virtual void OnFilterCellClick(wxGridEvent &event); // wxGlade: <event_handler>
    virtual void OnStartupPanelCombo(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnStartupCheckControl(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnStartupCheckRawData(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnStartupCheckPlotList(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCheckPreferOrtho(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnMouseMoveSlider(wxScrollEvent &event); // wxGlade: <event_handler>
    virtual void OnMouseZoomSlider(wxScrollEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // PREFDIALOG_H
